# ThymeLeaf
spring.thymeleaf.template-loader-path: classpath:/templates
spring.thymeleaf.suffix: .html
spring.thymeleaf.cache: false

#Spring Data JPA
spring.jpa.show-sql=true
spring.h2.console.enabled=true
